--- 
components: 
  schemas: 

    # This is the base definition of a PointOfInterest
    PointOfInterest: 
      $ref: "https://github.com/dpatil-fw/dataModel.PointOfInterest/blob/master/PointOfInterest/model.yaml#/PointOfInterest"


    # This is a base definition of a City Attraction
    Attraction: 
      $ref: "https://github.com/dpatil-fw/dataModel.PointOfInterest/blob/master/Attraction/model.yaml#/Attraction"
    # This is a base definition of a City FoodEstablishment
    FoodEstablishment: 
      $ref: "https://github.com/dpatil-fw/dataModel.PointOfInterest/blob/master/FoodEstablishment/model.yaml#/FoodEstablishment"
    # This is a base definition of a City LodgingBusiness
    LodgingBusiness: 
      $ref: "https://github.com/dpatil-fw/dataModel.PointOfInterest/blob/master/LodgingBusiness/model.yaml#/LodgingBusiness"
    # This is a base definition of a City MedicalOrganization
    MedicalOrganization: 
      $ref: "https://github.com/dpatil-fw/dataModel.PointOfInterest/blob/master/MedicalOrganization/model.yaml#/MedicalOrganization"
    # This is a base definition of a City Store
    Store: 
      $ref: "https://github.com/dpatil-fw/dataModel.PointOfInterest/blob/master/Store/model.yaml#/Store"

info: 
  description: "Base Model Definitions from Smart Data Models"
  title: Baseline Models
  version: "1.0.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object