---
components:
  schemas: 
    GovernmentOrganization: 
      allOf: 
        - 
          $ref: "https://raw.githubusercontent.com/dpatil-fw/dataModel.PointOfInterest/master/GovernmentOrganization/model.yaml#/GovernmentOrganization"
info:
  description: "This entity Type models Government Organizations in the city."
  title: GovernmentOrganization
  version: "1.0.0"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - GovernmentOrganization
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/dpatil-fw/dataModel.PointOfInterest/master/GovernmentOrganization/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/dpatil-fw/dataModel.PointOfInterest/master/GovernmentOrganization/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
