---
components:
  schemas: 
    FinancialService: 
      allOf: 
        - 
          $ref: "https://raw.githubusercontent.com/dpatil-fw/dataModel.PointOfInterest/master/FinancialService/model.yaml#/FinancialService"
info:
  description: "This entity Type models Financial Service in the city."
  title: FinancialService
  version: "1.0.0"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - FinancialService
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/dpatil-fw/dataModel.PointOfInterest/master/FinancialService/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/dpatil-fw/dataModel.PointOfInterest/master/FinancialService/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
